const c = @import("c.zig");
pub const hfdcan1 = @extern(?*c.FDCAN_HandleTypeDef, .{ .name = "hfdcan1" });
pub const hlpuart1 = @extern(?*c.UART_HandleTypeDef, .{ .name = "hlpuart1" });
pub const huart1 = @extern(?*c.UART_HandleTypeDef, .{ .name = "huart1" });
pub const hspi1 = @extern(?*c.SPI_HandleTypeDef, .{ .name = "hspi1" });
pub const htim1 = @extern(?*c.TIM_HandleTypeDef, .{ .name = "htim1" });
pub const htim2 = @extern(?*c.TIM_HandleTypeDef, .{ .name = "htim2" });
pub const htim3 = @extern(?*c.TIM_HandleTypeDef, .{ .name = "htim3" });
pub const htim8 = @extern(?*c.TIM_HandleTypeDef, .{ .name = "htim8" });
// pub const hpcd_USB_FS = @extern(?*c.PCD_HandleTypeDef, .{ .name = "hpcd_USB_FS" });
